name: Update Gutenberg Books

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout fetcher repo
        uses: actions/checkout@v4
        with:
          repository: axel709/book-fetch
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
          path: ./fetcher

      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: axel709/gutenberg_list
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
          path: ./repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix ./fetcher

      - name: Run fetcher
        run: node ./fetcher/src/server.js

      - name: Commit and push updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./repo
          commit_message: "Automatic update of Gutenberg books"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: main
